### ISSUE TITLE
Set up linting / prettier rules for project

### ISSUE THREAD

**Issue by AlexGaiser** [AlexGaiser/freepi#27]
@Scott-Ian  I can set up eslint in the project and afterwards we can meet about what rules we want to set up. We should also set up standards for formatting (I prefer to use prettier in vscode, personally)

**Comment by Scott-Ian** [comment]
@AlexGaiser  Please Do. It would be nice to have some styling rules to adhere to. It seems like our styles match up fairly well already, so I don't expect much issue.

**Comment by AlexGaiser** [comment]
@Scott-Ian you should make sure you have "format on save" enabeled on your vscode in addition to the rules included in projects.
