### ISSUE TITLE
Importing @freepi/core failure

### ISSUE THREAD

**Issue by Scott-Ian** [AlexGaiser/freepi#48]
Master branch is not currently functioning on my device. Import statements of @freepi/Core are failing. 

Hovering over the issues reads: 'Cannot find module @freepi/core or its corresponding type declarations'

Running npm install issues the warning: "freepi@0.0.1 No repository field"

Manually running "npm install @freepi/core returns the same as the general npm install

Due to this failure, tests won't operate, and our base.req.ts file is not functioning.

**Comment by AlexGaiser** [comment]
@Scott-Ian What imports are you looking at and what version of @freepi/core? 

If you want to install you should try removing node_modules and installing @freepi/core@latest to make sure you have the newest version. 

Are you developing this inside the freepi library or as a sample application?

**Comment by AlexGaiser** [comment]
I just tested it in  a node.js and React TypeScript application.

**Comment by Scott-Ian** [comment]
Deleted node_modules as suggested, and reinstalled.  That did not fix it. 

Using "npm install @freepi/core@latest" resolved the issue. 

Seems like the master version is default attempting to install version 0.0.1 for some reason? Not sure why, package.json does list versions from 1.0.10 and up.

**Comment by AlexGaiser** [comment]
Yes, I am not sure why but for some reason we need to keep installing every package @latest to make sure we get the most recent version
